#!/usr/bin/env python
"""Generate configs/labels/*.yaml from the structure names present in the dataset.

The six group files must partition the full structure set exactly: every structure
in exactly one group, nothing invented, nothing dropped. Deriving them from a real
subject's ``segmentations/`` directory and asserting the partition is cheaper and
safer than maintaining 117 names by hand across six files.

Usage:
    python scripts/gen_label_configs.py <dataset_root> [--subject s0010]

Pick a subject with all structures present (``s0010`` has all 117); the script
fails loudly if the chosen subject is missing any.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "configs" / "labels"

# Group membership rules, applied in order -- first match wins. Rules are prefix
# and exact-name based so a structure added in a future dataset release either
# lands somewhere sensible or falls through to `organs` and shows up in the diff.
#
# The split mirrors TotalSegmentator's: structures are grouped by tissue class so
# each high-resolution model sees a coherent, similarly-scaled set of targets.
GROUPS: list[tuple[str, dict]] = [
    (
        "vertebrae",
        {"prefixes": ("vertebrae_",), "exact": ()},
    ),
    (
        "bones",
        {
            "prefixes": ("rib_", "clavicula_", "scapula_", "humerus_", "femur_", "hip_"),
            "exact": ("costal_cartilages", "sternum", "sacrum", "skull"),
        },
    ),
    (
        "cardiac",
        {
            "prefixes": (
                "brachiocephalic_",
                "subclavian_artery_",
                "common_carotid_artery_",
                "iliac_artery_",
                "iliac_vena_",
                "atrial_appendage_",
            ),
            "exact": (
                "heart",
                "aorta",
                "superior_vena_cava",
                "inferior_vena_cava",
                "pulmonary_vein",
                "portal_vein_and_splenic_vein",
            ),
        },
    ),
    (
        "muscles",
        {
            "prefixes": ("gluteus_", "autochthon_", "iliopsoas_"),
            "exact": (),
        },
    ),
    # Catch-all. Anything not claimed above is a soft-tissue organ.
    ("organs", {"prefixes": (), "exact": ()}),
]

# Expected sizes, asserted so a silent regrouping can't slip through unnoticed.
EXPECTED = {
    "organs": 26,
    "vertebrae": 25,
    "cardiac": 18,
    "muscles": 10,
    "bones": 38,
}

HEADER = """# GENERATED by scripts/gen_label_configs.py -- do not edit by hand.
#
# Label indices are 1-based and contiguous; 0 is background. The order here is
# the order masks are stacked into the multilabel volume, and it is the order the
# trained model's output channels will be in, so it must never be reshuffled once
# a model has been trained against it.
"""


def assign_group(name: str) -> str:
    for group, rule in GROUPS:
        if name in rule["exact"] or name.startswith(rule["prefixes"]):
            return group
    return "organs"


def write_yaml(path: Path, group: str, names: list[str], source: str) -> None:
    lines = [HEADER, f"name: {group}", f"source: {source}", f"count: {len(names)}", "labels:"]
    width = max(len(n) for n in names)
    for i, n in enumerate(names, start=1):
        lines.append(f"  {n}:{' ' * (width - len(n))} {i}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("dataset_root", type=Path)
    ap.add_argument("--subject", default="s0010", help="subject to read structure names from")
    args = ap.parse_args()

    seg_dir = args.dataset_root / args.subject / "segmentations"
    if not seg_dir.is_dir():
        print(f"error: no segmentations dir at {seg_dir}", file=sys.stderr)
        return 1

    names = sorted(p.name[: -len(".nii.gz")] for p in seg_dir.glob("*.nii.gz"))
    if not names:
        print(f"error: no masks found in {seg_dir}", file=sys.stderr)
        return 1
    print(f"found {len(names)} structures in {args.subject}")

    buckets: dict[str, list[str]] = {g: [] for g, _ in GROUPS}
    for n in names:
        buckets[assign_group(n)].append(n)

    # The partition must be exact -- this is the whole point of generating.
    total = sum(len(v) for v in buckets.values())
    assert total == len(names), f"partition lost structures: {total} != {len(names)}"
    seen = sorted(x for v in buckets.values() for x in v)
    assert seen == names, "partition altered the structure set"

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    source = f"{args.dataset_root.name}/{args.subject}"

    write_yaml(OUT_DIR / "all117.yaml", "all117", names, source)
    print(f"  all117    {len(names):>3}  -> configs/labels/all117.yaml")

    bad = []
    for group, _ in GROUPS:
        members = buckets[group]
        write_yaml(OUT_DIR / f"{group}.yaml", group, members, source)
        exp = EXPECTED.get(group)
        flag = ""
        if exp is not None and exp != len(members):
            flag = f"  <-- EXPECTED {exp}"
            bad.append(group)
        print(f"  {group:<9} {len(members):>3}  -> configs/labels/{group}.yaml{flag}")

    if bad:
        print(f"\nerror: group size mismatch for {', '.join(bad)}", file=sys.stderr)
        print("Either the dataset changed or GROUPS/EXPECTED need updating.", file=sys.stderr)
        return 1

    print("\npartition verified: every structure in exactly one group")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
